### ISSUE TITLE
Add variables to access methods in template

### ISSUE THREAD

**Issue by sjelfull** [verbb/bugsnag#22]

**Comment by keyurshah** [comment]
this would be great to have!

**Comment by sjelfull** [comment]
Added a few like `{% do craft.bugsnag.metadata({ orderId: cart.id }) %}` to add metadata on the fly and `{{ craft.bugsnag.getBrowserConfig(true) }}` to get the config needed for the JS client.

**Comment by keyurshah** [comment]
That’s great. Is it possible to send to bugsnag directly from twig? I want to send something to bugsnag if the category had no items inside.

**Comment by engram-design** [comment]
Added `craft.bugsnag.handleException()` in [3.0.1](https://github.com/verbb/bugsnag/releases/tag/3.0.1)
